### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by marcelolx** [LFSCamargo/Chatify#13]
I was trying to start project following these steps [how-to-run-the-app](https://github.com/LFSCamargo/Chatify#how-to-run-the-app), but when i execute `yarn install` i'm facing this error.

```bash
[4/4] Building fresh packages...
[-/10] ⠂ waiting...
[-/10] ⠂ waiting...
[8/10] ⠂ @chatify/app
[-/10] ⠂ waiting...
error D:\git\Chatify\node_modules\@chatify\app: Command failed.
Exit code: 1
Command: yarn codegen
Arguments:
Directory: D:\git\Chatify\node_modules\@chatify\app
Output:
yarn run v1.16.0
$ apollo codegen:generate --localSchemaFile=data/schema.json --target=typescript && rm -rf __generated__
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'D:\git\Chatify\node_modules\node_modules\apollo\bin\run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

OS: Windows 10
NodeJS: 10.15.3
Yarn: 1.9.4
MongoDB: 4.0.10 (fresh installation).

Any tip not described on readme?

**Comment by marcelolx** [comment]
Solved, it's a bug in yarn for windows.

https://github.com/yarnpkg/yarn/issues/4564

**Comment by nemanjam** [comment]
How exactly did you solve this? I'm on Windows and when I apply `patch-yarn.js` from https://github.com/overthq/Auxilium/pull/123/commits/86fe190d3f310df96b7fa1fbe317da642cdd5e5f I get the following unresolved packages:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-callkeep.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-callkeep: None of the consumable configurations have attributes.
   > Could not resolve project :react-native-image-resizer.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-image-resizer: None of the consumable configurations have attributes.
   > Could not resolve project :WebRTCModule.
     Required by:
         project :app
      > Unable to find a matching configuration of project :WebRTCModule: None of the consumable configurations have attributes.
   > Could not resolve project :react-native-image-picker.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-image-picker: None of the consumable configurations have attributes.
   > Could not resolve project :react-native-gesture-handler.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-gesture-handler: None of the consumable configurations have attributes.
   > Could not resolve project :react-native-fetch-blob.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-fetch-blob: None of the consumable configurations have attributes.
```

**Comment by marcelolx** [comment]
@nemanjam I switched to linux 🤸‍♂
